# Generated by Django 5.2.5 on 2025-09-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='full_name',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/default-profile.png', null=True, upload_to='profile_pics/students/'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/default-profile.png', null=True, upload_to='profile_pics/teacher/'),
        ),
    ]
