# Generated by Django 5.2.5 on 2025-09-26 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_studentprofile_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='static/images/default-profile.png', null=True, upload_to='profile_pics/students/'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='static/images/default-profile.png', null=True, upload_to='profile_pics/teacher/'),
        ),
    ]
