# Generated by Django 5.2.5 on 2025-09-26 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_studentprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default-profile.png', null=True, upload_to='profile_pics/students/'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default-profile.png', null=True, upload_to='profile_pics/teacher/'),
        ),
    ]
