# Generated by Django 5.2.5 on 2025-09-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_studentprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
