# Generated by Django 5.2.5 on 2025-09-26 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_studentprofile_middle_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='section',
        ),
    ]
