# Generated by Django 5.2.5 on 2025-10-04 10:44

import room.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='resource_url',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='file_url',
        ),
        migrations.AddField(
            model_name='activity',
            name='resource_file',
            field=models.FileField(blank=True, null=True, upload_to=room.models.activity_resource_upload_path),
        ),
        migrations.AddField(
            model_name='submission',
            name='submission_file',
            field=models.FileField(blank=True, null=True, upload_to=room.models.submission_upload_path),
        ),
    ]
