# Generated by Django 5.2.5 on 2025-09-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('submitted', 'Submitted'), ('graded', 'Graded'), ('closed', 'Closed')], default='open', max_length=20),
        ),
    ]
