# Generated by Django 5.2.5 on 2025-10-04 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_remove_activity_resource_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('activity_graded', 'Activity Graded'), ('new_activity', 'New Activity Assigned'), ('new_announcement', 'New Announcement'), ('activity_due_soon', 'Activity Due Soon'), ('activity_overdue', 'Activity Overdue'), ('room_update', 'Room Updated'), ('student_submitted', 'Student Submitted'), ('student_enrolled', 'Student Enrolled'), ('student_left', 'Student Left Room'), ('activity_due_reminder', 'Activity Due Reminder'), ('submission_overdue', 'Submission Overdue')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='room.activity')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_notifications', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='room.room')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='room.submission')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='room_notifi_recipie_7a8587_idx'), models.Index(fields=['created_at'], name='room_notifi_created_a9c7eb_idx')],
            },
        ),
    ]
