# Generated by Django 5.2.5 on 2025-09-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_alter_room_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
    ]
