# Generated by Django 5.2.5 on 2025-09-25 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_alter_activity_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
    ]
