# Generated by Django 5.2.5 on 2025-11-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='base_passing',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
