# Generated by Django 5.2.5 on 2025-09-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_activity_due_date_activity_total_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
