# Generated by Django 5.2.5 on 2025-09-26 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_submission_status_alter_activity_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='room.room'),
        ),
    ]
