# Generated by Django 5.2.5 on 2025-09-23 03:47

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_activity_active'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='resource',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='resource'),
        ),
        migrations.AlterField(
            model_name='room',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.teacherprofile'),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='submission_file')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.activity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.studentprofile')),
            ],
        ),
    ]
