# Generated by Django 5.2.5 on 2025-09-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_alter_activity_resource_alter_room_teacher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='active',
        ),
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('graded', 'Graded'), ('closed', 'Closed')], default='open', max_length=20),
        ),
    ]
