# Generated by Django 5.2.5 on 2025-09-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_remove_activity_active_activity_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
